### ISSUE TITLE
Updates with 1.0.0 nightlies

### ISSUE THREAD

**Issue by Ap0ph1s** [mahkoh/scan#5]
Really think this lib is useful, any news about updating soon, doesnt compile atm.

**Comment by mahkoh** [comment]
Fixed in https://github.com/mahkoh/scan/commit/c6051159c9b44a71348e7317283869f1204dd803

**Comment by Ap0ph1s** [comment]
Thanks for the quick fix! however the example you put in the README.md is out of date with using plugins and feature phase, and since Im sort of a noob, I dont know exactly what to replace or take out, any help?

**Comment by mahkoh** [comment]
There is an example in the examples directory.

**Comment by Ap0ph1s** [comment]
Thanks again!
